### ISSUE TITLE
customCounters in config.json

### ISSUE THREAD

**Issue by marsu95** [MindFlavor/prometheus_sql_server_exporter#27]
Hi,
thanks for this nice job, I did installed it on an ubuntu (20.04 LTS) server, without docker and dotnet version is 3.1.404.
I installed an sqlserver (15.0.4102.2) on this server.
I'd like to use the part named customCounters in the config file, but it seems not working, is there a special option or parameter to mention somewhere ?
To illustrate, if needed (from sample) : 
    "customCounters": [
        {
            "customCounter": {
                "name": "sql_user_sessions",
                "tsql": "SELECT [status], COUNT(*) AS cnt FROM sys.dm_exec_requests WHERE session_id > 50 GROUP BY [status];",
                "type": "gauge",
                "help_text": "Current user sessions",
                "attributes": [
                    "status"
                ],
                "value": "cnt"
            }
        },

Just for details, a part of the metrics avaible : 
sql_os_schedulers_is_online{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 1
sql_os_schedulers_is_idle{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 0
sql_os_schedulers_preemptive_switches_count{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 186071
sql_os_schedulers_context_switches_count{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 7660843
sql_os_schedulers_idle_switches_count{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 13934485
sql_os_schedulers_current_tasks_count{instance="SWB02", parent_node_id="0", scheduler_id="0", cpu_id="0"} 11
Nothing else than "sql_os_schedulers..."
Thanks in advance
Rm *

**Comment by MindFlavor** [comment]
Hi @marsu95, it seems you are right, the custom counters aren't returned. 
I'll take a look into it!

**Comment by MindFlavor** [comment]
Please let me know if the .net version upgrade fixes your issue!

**Comment by marsu95** [comment]
Thanks to take a part of your time to consider this.
I've just token in count this new version, on ubuntu 20.04.
Now, with sdk5 (not "dotnet bin/Release/netcoreapp3.1.." any more but "dotnet bin/Release/netcoreapp5.0...") 
I did test the given example for "sql_user_sessions", the request is quite correct, but no such counter available on port 9966.
Did I miss somehting ?
Side way, I'm wondering, 37 processes for dotnet, even for 3 sql instances, is it usual ?
